// GENERATED by tools/import-overworld.mjs — do not edit by hand.
import { Presets } from '@rpgjs/client'

export const OW_TICKERS = ["AAOI","AAPL","ABCL","ADBE","AEHR","AEIS","ALAB","AMAT","AMBA","AMC","AMD","AMKR","AMZN","ANET","APLD","APP","ASML","ASTS","AUR","AVAV","AVGO","AXON","AXTI","BA","BABA","BB","BE","BND","BULL","CBRS","CCL","CEG","CELH","CIEN","CLOV","CLS","CLSK","COHR","COIN","COST","CRCL","CRDO","CRM","CRWD","CRWV","CSCO","CTSH","CVNA","DDOG","DELL","DJT","DOCN","ELF","EWT","EWY","F","FICO","FIG","FISV","GOOGL","META","MSFT","MSTR","NFLX","NVDA","PLTR","TSLA","WIF"] as const

// 128x128 RPG Maker charsets: 4 frames x 4 directions
export const owSpritesheets = OW_TICKERS.map((t) => ({
  id: `ow-${t}`,
  image: `spritesheets/ow/${t}.png`,
  ...Presets.RMSpritesheet(4, 4),
}))
