/*
 * map-browser.ts — the in-game WORLD MAP / fast-travel window.
 *
 *   mountMapBrowser(engine, socket)   // create it (hidden) at boot
 *   openMapBrowser()                  // open it from anywhere (HUD MAP button)
 *
 * Structure — deliberately the marketplace's shape, so the two windows feel
 * like one program:
 *   ┌ titlebar (draggable) · place count · close ───────────────────────────┐
 *   │ sidebar: search + region list │ toolbar + card grid                   │
 *   └───────────────────────────────────────────────────────────────────────┘
 *   One sub-sheet overlays the window: the map detail / TRAVEL HERE panel,
 *   modelled on the marketplace's purchase sheet.
 *
 * Data comes from src/data/map-catalog.ts, generated by
 * tools/render-map-thumbs.mjs together with the preview PNGs in
 * public/mapthumbs/. There are 171 maps, so every thumbnail is fetched only
 * once its card scrolls into view (IntersectionObserver, below) — otherwise
 * opening the window would kick off 171 image requests at once.
 *
 * Travel is one line: `engine.processAction('travel:to', { map })`. The server
 * owns the destination tile and the validation; this window never guesses at
 * coordinates and never emits anything else.
 *
 * z-index: the marketplace's band (960-990), i.e. above the map canvas and the
 * HUD but below the RPG-JS dialog layer — and it hides itself while a game
 * dialog is up (`watchGameDialog`) instead of fighting it.
 */

import { MAP_CATALOG, REGION_LABELS, type MapCatalogEntry, type MapRegion } from './data/map-catalog'
import {
  ensureUiKit, injectStyle, el, guardKeys, pushLayer,
  makeDraggable, watchGameDialog, Z,
} from './ui-kit'

/* ================================================================= TYPES ===*/

export type RegionFilter = 'all' | MapRegion
export type MapSortKey = 'name' | 'size-desc' | 'size-asc'

interface EngineLike { processAction?: (action: string, data: unknown) => void }
interface SocketLike { on?: (type: string, cb: (data: any) => void) => void }

export interface MapBrowserApi {
  open(): void
  close(): void
  toggle(): void
  isOpen(): boolean
  /** Open the window straight onto one map's detail sheet. */
  show(mapId: string): void
  destroy(): void
  root: HTMLElement
}

/* ================================================================ STYLES ===*/

/** Region accent colours — the same palette family as the marketplace chips. */
const REGION_COLORS: Record<MapRegion, string> = {
  exchange: '#f6c177',
  kanto: '#6fa8f5',
  johto: '#7ecf6b',
  other: '#b9b2d6',
}

const CSS = `
#sm-mapbrowser {
  z-index: ${Z.marketWindow};
  width: min(1180px, 94vw); height: min(760px, 88vh);
  left: 50%; top: 50%; transform: translate(-50%, -50%);
  display: none;
}
#sm-mapbrowser.open { display: flex; }
#sm-mapbrowser.dialog-hidden { visibility: hidden; pointer-events: none; }

/* --- title bar ----------------------------------------------------------- */
#sm-mapbrowser .mb-count-chip {
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--sm-surface); border: 2px solid var(--sm-border);
  padding: 4px 8px; font-size: 10px; letter-spacing: .06em; line-height: 1;
}
#sm-mapbrowser .mb-count-chip .dot { width: 7px; height: 7px; background: var(--sm-ok); }

/* --- body ---------------------------------------------------------------- */
#sm-mapbrowser .mb-body { flex: 1 1 auto; display: flex; min-height: 0; }
#sm-mapbrowser .mb-side {
  flex: 0 0 224px; min-height: 0;
  display: flex; flex-direction: column;
  background: var(--sm-dark);
  border-right: 3px solid var(--sm-border);
}
#sm-mapbrowser .mb-search { padding: 12px; border-bottom: 3px solid rgba(246,193,119,.24); }
#sm-mapbrowser .mb-regions { flex: 1 1 auto; min-height: 0; padding: 10px 12px 12px; }
#sm-mapbrowser .mb-regions h5 {
  margin: 0 0 8px;
  font-size: 10px; font-weight: 700; letter-spacing: .14em;
  color: var(--sm-border); text-transform: uppercase;
}
#sm-mapbrowser .mb-region {
  width: 100%;
  display: flex; align-items: center; gap: 8px;
  font-family: inherit; font-size: 11px; font-weight: 700; letter-spacing: .06em;
  text-transform: uppercase;
  color: var(--sm-muted);
  background: transparent;
  border: 3px solid transparent;
  border-radius: 0;
  padding: 8px 9px; margin: 0 0 4px;
  cursor: pointer; text-align: left;
}
#sm-mapbrowser .mb-region:hover { color: var(--sm-text); background: rgba(246,193,119,.1); }
#sm-mapbrowser .mb-region.is-on {
  color: #09070f; background: var(--sm-border); border-color: var(--sm-border);
  box-shadow: 3px 3px 0 var(--sm-shadow);
}
#sm-mapbrowser .mb-region .sw { width: 9px; height: 9px; flex: 0 0 9px; border: 1px solid rgba(9,7,15,.6); }
#sm-mapbrowser .mb-region .lb { flex: 1 1 auto; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
#sm-mapbrowser .mb-region .n { opacity: .75; font-size: 10px; }
#sm-mapbrowser .mb-hint {
  margin-top: 14px; padding: 8px 0 0;
  border-top: 2px solid rgba(246,193,119,.18);
  font-size: 10px; line-height: 1.6; letter-spacing: .04em; color: var(--sm-muted);
}

/* --- main ---------------------------------------------------------------- */
#sm-mapbrowser .mb-main { flex: 1 1 auto; min-width: 0; display: flex; flex-direction: column; }
#sm-mapbrowser .mb-toolbar {
  flex: 0 0 auto;
  display: flex; align-items: center; gap: 12px;
  padding: 10px 14px;
  border-bottom: 3px solid rgba(246,193,119,.24);
  background: rgba(27,23,48,.55);
  font-size: 11px; letter-spacing: .08em; color: var(--sm-muted);
}
#sm-mapbrowser .mb-toolbar .spacer { flex: 1 1 auto; }
#sm-mapbrowser .mb-toolbar strong { color: var(--sm-text); }
#sm-mapbrowser select.smui-input { width: auto; padding: 6px 8px; cursor: pointer; }
#sm-mapbrowser .mb-grid {
  flex: 1 1 auto; min-height: 0;
  padding: 14px;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(196px, 1fr));
  gap: 14px;
  align-content: start;
}
#sm-mapbrowser .mb-empty {
  grid-column: 1 / -1;
  padding: 48px 12px; text-align: center;
  color: var(--sm-muted); font-size: 12px; letter-spacing: .1em;
}

/* --- card ---------------------------------------------------------------- */
#sm-mapbrowser .mb-card {
  display: flex; flex-direction: column; gap: 8px;
  padding: 10px;
  background: var(--sm-surface-alt);
  border: 3px solid var(--sm-border);
  box-shadow: 3px 3px 0 var(--sm-shadow);
}
#sm-mapbrowser .mb-card:hover { background: #362f56; }
#sm-mapbrowser .mb-open {
  display: flex; flex-direction: column; gap: 7px;
  padding: 0; margin: 0;
  background: none; border: none; border-radius: 0;
  font-family: inherit; color: inherit; text-align: left;
  cursor: pointer;
}
#sm-mapbrowser .mb-shot {
  position: relative;
  aspect-ratio: 4 / 3;
  background:
    radial-gradient(circle at 50% 45%, rgba(246,193,119,.13), transparent 68%),
    linear-gradient(#1d1834, #14101f);
  border: 2px solid rgba(246,193,119,.42);
  display: flex; align-items: center; justify-content: center;
  overflow: hidden;
}
#sm-mapbrowser .mb-shot img {
  position: relative; z-index: 1;
  max-width: 100%; max-height: 100%;
  object-fit: contain;
  image-rendering: pixelated;
  opacity: 0; transition: opacity .12s linear;
}
#sm-mapbrowser .mb-shot img.is-loaded { opacity: 1; }
/* Sits *under* the image: the glyph is what the player sees until it lands. */
#sm-mapbrowser .mb-shot .ph {
  position: absolute; inset: 0; z-index: 0;
  display: flex; align-items: center; justify-content: center;
  font-size: 18px; color: rgba(246,193,119,.28);
}
/* Above the thumbnail (which carries z-index 1 of its own), never under it. */
#sm-mapbrowser .mb-shot .chip {
  position: absolute; top: 5px; left: 5px; z-index: 2;
  padding: 2px 5px; line-height: 1;
  font-size: 8px; font-weight: 700; letter-spacing: .08em;
  color: #09070f; border: 1px solid rgba(9,7,15,.55);
  box-shadow: 1px 1px 0 rgba(9,7,15,.7);
}
#sm-mapbrowser .mb-card .name {
  font-size: 12px; font-weight: 700; letter-spacing: .04em;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
#sm-mapbrowser .mb-card .sub {
  display: flex; align-items: center; gap: 8px; flex-wrap: wrap;
  font-size: 9px; letter-spacing: .06em; color: var(--sm-muted);
  min-height: 12px;
}
#sm-mapbrowser .mb-card .smui-btn { width: 100%; padding: 8px 6px; font-size: 11px; }

/* --- detail sheet -------------------------------------------------------- */
#sm-mapbrowser .mb-modal {
  position: absolute; inset: 0; z-index: ${Z.marketModal - Z.marketWindow + 10};
  background: rgba(9,7,15,.82);
  display: none; align-items: center; justify-content: center;
  padding: 20px;
}
#sm-mapbrowser .mb-modal.open { display: flex; }
#sm-mapbrowser .mb-modal .sheet {
  width: min(680px, 100%); max-height: 100%;
  display: flex; flex-direction: column;
  background: var(--sm-surface);
  border: 3px solid var(--sm-border);
  box-shadow: 6px 6px 0 var(--sm-shadow);
  overflow: hidden;
}
#sm-mapbrowser .mb-modal .sheet > .head {
  display: flex; align-items: center; gap: 10px;
  padding: 10px 12px; background: var(--sm-dark);
  border-bottom: 3px solid var(--sm-border);
}
#sm-mapbrowser .mb-modal .sheet > .head .title {
  font-family: "Fredoka", "Trebuchet MS", sans-serif;
  font-weight: 600; font-size: 14px; letter-spacing: .14em;
  text-shadow: 2px 2px 0 var(--sm-shadow);
}
#sm-mapbrowser .mb-modal .sheet > .head .spacer { flex: 1 1 auto; }
#sm-mapbrowser .mb-modal .sheet > .content {
  padding: 16px; display: flex; flex-direction: column; gap: 14px;
  overflow-y: auto; min-height: 0;
}
#sm-mapbrowser .mb-bigshot {
  height: 268px; flex: 0 0 auto;
  background:
    radial-gradient(circle at 50% 45%, rgba(246,193,119,.16), transparent 68%),
    linear-gradient(#1d1834, #14101f);
  border: 3px solid var(--sm-border);
  display: flex; align-items: center; justify-content: center;
  overflow: hidden;
}
#sm-mapbrowser .mb-bigshot img {
  max-width: 100%; max-height: 100%;
  object-fit: contain; image-rendering: pixelated;
}
#sm-mapbrowser .mb-modal .info { display: flex; flex-direction: column; gap: 10px; min-width: 0; }
#sm-mapbrowser .mb-modal .info h3 {
  margin: 0; font-family: "Fredoka", "Trebuchet MS", sans-serif;
  font-size: 18px; font-weight: 600; letter-spacing: .06em;
  text-shadow: 2px 2px 0 var(--sm-shadow);
}
#sm-mapbrowser .mb-attrs { border: 2px solid rgba(246,193,119,.32); }
#sm-mapbrowser .mb-attrs .r { display: flex; gap: 10px; padding: 5px 8px; font-size: 10px; letter-spacing: .05em; }
#sm-mapbrowser .mb-attrs .r:nth-child(odd) { background: rgba(27,23,48,.55); }
#sm-mapbrowser .mb-attrs .r .k { flex: 0 0 104px; color: var(--sm-muted); font-weight: 700; }
#sm-mapbrowser .mb-attrs .r .v { flex: 1 1 auto; min-width: 0; overflow: hidden; text-overflow: ellipsis; }
#sm-mapbrowser .mb-links { display: flex; flex-wrap: wrap; gap: 6px; }
#sm-mapbrowser .mb-link {
  font-family: inherit; font-size: 10px; font-weight: 700; letter-spacing: .05em;
  color: var(--sm-text); background: var(--sm-dark);
  border: 2px solid var(--sm-border); border-radius: 0;
  padding: 4px 7px; line-height: 1; cursor: pointer;
}
#sm-mapbrowser .mb-link:hover { background: #3a3358; }
#sm-mapbrowser .mb-note {
  font-size: 10px; line-height: 1.6; letter-spacing: .04em; color: var(--sm-muted);
  border-left: 3px solid var(--sm-border); padding: 4px 0 4px 8px;
}
#sm-mapbrowser .mb-modal .foot {
  display: flex; align-items: center; gap: 12px;
  padding: 12px 16px; background: var(--sm-dark);
  border-top: 3px solid var(--sm-border);
}
#sm-mapbrowser .mb-modal .foot .spacer { flex: 1 1 auto; }
#sm-mapbrowser .mb-modal .foot .dest { display: flex; flex-direction: column; gap: 3px; min-width: 0; }
#sm-mapbrowser .mb-modal .foot .dest .k { font-size: 9px; letter-spacing: .16em; color: var(--sm-muted); }
#sm-mapbrowser .mb-modal .foot .dest .v {
  font-size: 16px; font-weight: 700; color: var(--sm-border); letter-spacing: .04em;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}
#sm-mapbrowser .mb-modal .foot .smui-btn { min-width: 128px; text-align: center; }

@media (max-width: 900px) {
  #sm-mapbrowser .mb-side { flex-basis: 176px; }
  #sm-mapbrowser .mb-bigshot { height: 190px; }
}
`

/* ================================================================== VIEW ===*/

const REGION_ORDER: RegionFilter[] = ['all', 'exchange', 'kanto', 'johto', 'other']

const tiles = (m: MapCatalogEntry) => m.width * m.height

let instance: MapBrowserApi | null = null

export function mountMapBrowser(engine?: EngineLike, socket?: SocketLike): MapBrowserApi {
  if (instance) return instance
  ensureUiKit()
  injectStyle('sm-mapbrowser-css', CSS)

  const byId = new Map(MAP_CATALOG.map((m) => [m.id, m]))
  let region: RegionFilter = 'all'
  let query = ''
  let sort: MapSortKey = 'name'
  let visible: MapCatalogEntry[] = []

  /* --- chrome ------------------------------------------------------------ */
  const root = el('div', {
    id: 'sm-mapbrowser', class: 'smui smui-win',
    role: 'dialog', 'aria-label': 'World map', 'aria-modal': 'false',
  })

  const titlebar = el('div', { class: 'smui-titlebar' })
  const countChip = el('span', { class: 'mb-count-chip' }, [
    el('span', { class: 'dot' }),
    el('span', { text: `${MAP_CATALOG.length} PLACES` }),
  ])
  const closeBtn = el('button', {
    class: 'smui-btn smui-close is-danger', type: 'button',
    'aria-label': 'Close world map', text: '✕',
  })
  titlebar.append(
    el('span', { class: 'title', text: 'WORLD MAP' }),
    el('span', { class: 'spacer' }),
    countChip,
    closeBtn,
  )

  /* --- sidebar ----------------------------------------------------------- */
  const search = el('input', {
    class: 'smui-input', type: 'search', placeholder: 'Search places…',
    'aria-label': 'Search maps', autocomplete: 'off', spellcheck: 'false',
  })
  guardKeys(search)
  let searchTimer: any = null
  search.addEventListener('input', () => {
    clearTimeout(searchTimer)
    searchTimer = setTimeout(() => { query = search.value.trim().toLowerCase(); refresh() }, 120)
  })

  const regionBtns = new Map<RegionFilter, HTMLButtonElement>()
  const regionList = el('div', { role: 'tablist', 'aria-label': 'Region' })
  for (const r of REGION_ORDER) {
    const label = r === 'all' ? 'All' : REGION_LABELS[r]
    const n = r === 'all' ? MAP_CATALOG.length : MAP_CATALOG.filter((m) => m.region === r).length
    const b = el('button', {
      class: `mb-region${r === 'all' ? ' is-on' : ''}`, type: 'button',
      role: 'tab', 'aria-selected': r === 'all' ? 'true' : 'false', 'data-region': r,
    }, [
      el('span', { class: 'sw', style: `background:${r === 'all' ? 'var(--sm-text)' : REGION_COLORS[r]}` }),
      el('span', { class: 'lb', text: label }),
      el('span', { class: 'n', text: String(n) }),
    ])
    b.addEventListener('click', () => setRegion(r))
    regionBtns.set(r, b)
    regionList.appendChild(b)
  }

  const side = el('div', { class: 'mb-side' }, [
    el('div', { class: 'mb-search' }, [search]),
    el('div', { class: 'mb-regions smui-scroll' }, [
      el('h5', { text: 'Region' }),
      regionList,
      el('div', {
        class: 'mb-hint',
        text: 'Pick a place to see its preview, size and the maps it borders. Travel is instant.',
      }),
    ]),
  ])

  /* --- main -------------------------------------------------------------- */
  const countEl = el('strong', { text: '—' })
  const sortSel = el('select', { class: 'smui-input', 'aria-label': 'Sort maps' })
  for (const [v, label] of [
    ['name', 'Name A-Z'], ['size-desc', 'Largest first'], ['size-asc', 'Smallest first'],
  ] as const) sortSel.appendChild(el('option', { value: v, text: label }))
  sortSel.addEventListener('change', () => { sort = sortSel.value as MapSortKey; refresh() })
  guardKeys(sortSel)

  const toolbar = el('div', { class: 'mb-toolbar' }, [
    countEl, el('span', { text: 'PLACES' }),
    el('span', { class: 'spacer' }),
    el('span', { text: 'SORT' }), sortSel,
  ])
  const grid = el('div', { class: 'mb-grid smui-scroll' })
  const main = el('div', { class: 'mb-main' }, [toolbar, grid])

  const body = el('div', { class: 'mb-body' }, [side, main])
  const modal = el('div', { class: 'mb-modal' })

  root.append(titlebar, body, modal)
  document.body.appendChild(root)
  makeDraggable(root, titlebar)

  /* --------------------------------------------------- lazy thumbnails --- */
  /*
   * 171 maps means 171 PNGs. Fetch one only when its card is near the viewport;
   * `rootMargin` gives the image a screenful of runway so it is usually decoded
   * by the time the player scrolls to it. Older engines with no
   * IntersectionObserver just load everything, which is the old behaviour and
   * still correct.
   */
  const io = typeof IntersectionObserver !== 'undefined'
    ? new IntersectionObserver((entries, obs) => {
      for (const e of entries) {
        if (!e.isIntersecting) continue
        const img = e.target as HTMLImageElement
        obs.unobserve(img)
        loadThumb(img)
      }
    }, { root: grid, rootMargin: '300px 0px' })
    : null

  function loadThumb(img: HTMLImageElement) {
    const src = img.dataset.src
    if (!src || img.getAttribute('src')) return
    img.addEventListener('load', () => img.classList.add('is-loaded'), { once: true })
    img.addEventListener('error', () => { img.remove() }, { once: true })
    img.setAttribute('src', src)
  }

  function thumbNode(m: MapCatalogEntry, eager = false): HTMLElement {
    const img = el('img', {
      alt: `${m.name} preview`, draggable: 'false', decoding: 'async', loading: 'lazy',
    }) as HTMLImageElement
    img.dataset.src = m.thumb
    if (eager || !io) loadThumb(img)
    else io.observe(img)
    return img
  }

  /* --------------------------------------------------------------- render */
  function regionChip(m: MapCatalogEntry): HTMLElement {
    return el('span', {
      class: 'chip',
      style: `background:${REGION_COLORS[m.region]}`,
      text: REGION_LABELS[m.region].toUpperCase(),
    })
  }

  function card(m: MapCatalogEntry): HTMLElement {
    const shot = el('div', { class: 'mb-shot' }, [
      el('span', { class: 'ph', text: '▦', 'aria-hidden': 'true' }),
      thumbNode(m),
      regionChip(m),
    ])
    const openBtn = el('button', {
      class: 'mb-open', type: 'button',
      'aria-label': `${m.name} — details`, title: m.name,
    }, [
      shot,
      el('span', { class: 'name', text: m.name }),
      el('span', { class: 'sub' }, [
        el('span', { text: `${m.width}×${m.height} TILES` }),
        m.connections.length ? el('span', { text: `⇄ ${m.connections.length}` }) : null,
      ]),
    ])
    openBtn.addEventListener('click', () => openDetail(m.id))

    const travel = el('button', { class: 'smui-btn is-primary', type: 'button', text: 'Travel' })
    travel.addEventListener('click', (e) => { e.stopPropagation(); doTravel(m) })

    return el('div', { class: 'mb-card' }, [openBtn, travel])
  }

  function compute(): MapCatalogEntry[] {
    const q = query
    const out = MAP_CATALOG.filter((m) => {
      if (region !== 'all' && m.region !== region) return false
      if (!q) return true
      return `${m.name} ${m.id} ${REGION_LABELS[m.region]}`.toLowerCase().includes(q)
    })
    if (sort === 'size-desc') out.sort((a, b) => tiles(b) - tiles(a) || a.name.localeCompare(b.name))
    else if (sort === 'size-asc') out.sort((a, b) => tiles(a) - tiles(b) || a.name.localeCompare(b.name))
    else out.sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id))
    return out
  }

  function refresh() {
    visible = compute()
    countEl.textContent = String(visible.length)
    io?.disconnect()
    grid.textContent = ''
    if (!visible.length) {
      grid.appendChild(el('div', { class: 'mb-empty', text: 'NO PLACES MATCH THIS SEARCH' }))
      return
    }
    const frag = document.createDocumentFragment()
    for (const m of visible) frag.appendChild(card(m))
    grid.appendChild(frag)
  }

  function setRegion(r: RegionFilter) {
    region = r
    for (const [id, b] of regionBtns) {
      const on = id === r
      b.classList.toggle('is-on', on)
      b.setAttribute('aria-selected', String(on))
    }
    grid.scrollTop = 0
    refresh()
  }

  /* ---------------------------------------------------------- detail sheet */
  let releaseSheet: (() => void) | null = null

  function closeDetail() {
    modal.classList.remove('open')
    modal.textContent = ''
    releaseSheet?.()
    releaseSheet = null
  }

  function attrRow(k: string, v: Node | string): HTMLElement {
    return el('div', { class: 'r' }, [
      el('span', { class: 'k', text: k }),
      typeof v === 'string'
        ? el('span', { class: 'v', text: v, title: v })
        : el('span', { class: 'v' }, [v]),
    ])
  }

  function openDetail(id: string) {
    const m = byId.get(id)
    if (!m) return
    const wasOpen = !!releaseSheet
    modal.textContent = ''

    const links = el('div', { class: 'mb-links' })
    const neighbours = m.connections.map((c) => byId.get(c)).filter(Boolean) as MapCatalogEntry[]
    if (neighbours.length) {
      for (const n of neighbours) {
        const b = el('button', { class: 'mb-link', type: 'button', text: n.name })
        b.addEventListener('click', () => openDetail(n.id))
        links.appendChild(b)
      }
    } else {
      links.appendChild(el('span', {
        class: 'mb-note', style: 'border:none;padding:0',
        text: 'No recorded edge links — reachable by fast travel only.',
      }))
    }

    const attrs = el('div', { class: 'mb-attrs' }, [
      attrRow('REGION', REGION_LABELS[m.region]),
      attrRow('SIZE', `${m.width} × ${m.height} tiles (${m.width * 32} × ${m.height * 32} px)`),
      attrRow('MAP ID', m.id),
      attrRow('BORDERS', links),
    ])

    const travelBtn = el('button', { class: 'smui-btn is-primary', type: 'button', text: 'Travel here' })
    const cancelBtn = el('button', { class: 'smui-btn', type: 'button', text: 'Back' })

    const sheet = el('div', { class: 'sheet' }, [
      el('div', { class: 'head' }, [
        el('span', { class: 'title', text: 'FAST TRAVEL' }),
        el('span', { class: 'spacer' }),
      ]),
      el('div', { class: 'content smui-scroll' }, [
        el('div', { class: 'mb-bigshot' }, [thumbNode(m, true)]),
        el('div', { class: 'info' }, [
          el('h3', { text: m.name }),
          attrs,
          el('div', {
            class: 'mb-note',
            text: 'You arrive at this map\'s designated landing tile. The server picks the exact spot and refuses anywhere you are not allowed to be.',
          }),
        ]),
      ]),
      el('div', { class: 'foot' }, [
        el('div', { class: 'dest' }, [
          el('span', { class: 'k', text: 'DESTINATION' }),
          el('span', { class: 'v', text: m.name, title: m.name }),
        ]),
        el('span', { class: 'spacer' }),
        cancelBtn, travelBtn,
      ]),
    ])

    modal.appendChild(sheet)
    modal.classList.add('open')
    // Re-entering the sheet from a BORDERS link must not stack ESC layers.
    if (!wasOpen) releaseSheet = pushLayer(closeDetail)
    cancelBtn.addEventListener('click', closeDetail)
    travelBtn.addEventListener('click', () => doTravel(m))
    setTimeout(() => travelBtn.focus(), 0)
  }

  /* ---------------------------------------------------------------- travel */
  function doTravel(m: MapCatalogEntry) {
    engine?.processAction?.('travel:to', { map: m.id })
    close()
  }

  /* -------------------------------------------------------- open / close */
  let releaseWindow: (() => void) | null = null
  function open() {
    if (root.classList.contains('open')) return
    root.classList.add('open')
    releaseWindow = pushLayer(() => close())
    refresh()
    setTimeout(() => search.focus(), 0)
  }
  function close() {
    closeDetail()
    root.classList.remove('open')
    releaseWindow?.()
    releaseWindow = null
  }
  closeBtn.addEventListener('click', () => close())

  // Never fight the RPG-JS dialog layer: step aside while a dialog is up.
  const stopWatch = watchGameDialog((dialogOpen) => {
    root.classList.toggle('dialog-hidden', dialogOpen)
  })

  // Optional server push, harmless if the event never fires.
  socket?.on?.('map:browser', (d: { map?: string }) => {
    if (d?.map) api.show(d.map)
    else open()
  })

  const api: MapBrowserApi = {
    root,
    open,
    close,
    toggle() { root.classList.contains('open') ? close() : open() },
    isOpen: () => root.classList.contains('open'),
    show(mapId) { open(); openDetail(mapId) },
    destroy() {
      stopWatch()
      io?.disconnect()
      close()
      root.remove()
      instance = null
    },
  }
  instance = api
  return api
}

/** Open the world map, mounting it on first use. */
export function openMapBrowser(): MapBrowserApi {
  const api = instance ?? mountMapBrowser()
  api.open()
  return api
}

export function closeMapBrowser(): void { instance?.close() }
export function getMapBrowser(): MapBrowserApi | null { return instance }
