<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/azalea-town.tmx — do not edit.
     Holds only the 260 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="azalea-town-compact" tilewidth="32" tileheight="32" tilecount="260" columns="17">
 <image source="azalea-town.png" width="544" height="512"/>
</tileset>
