<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/basement.tmx — do not edit.
     Holds only the 202 tiles that map draws, plus every frame of the
     5 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="basement-compact" tilewidth="32" tileheight="32" tilecount="202" columns="15">
 <image source="basement.png" width="480" height="448"/>
 <tile id="0">
  <animation>
   <frame tileid="0" duration="100"/>
   <frame tileid="1" duration="100"/>
   <frame tileid="2" duration="100"/>
   <frame tileid="3" duration="100"/>
   <frame tileid="4" duration="100"/>
   <frame tileid="5" duration="100"/>
   <frame tileid="6" duration="100"/>
   <frame tileid="7" duration="100"/>
   <frame tileid="8" duration="100"/>
   <frame tileid="9" duration="100"/>
   <frame tileid="10" duration="100"/>
   <frame tileid="11" duration="100"/>
  </animation>
 </tile>
 <tile id="12">
  <animation>
   <frame tileid="12" duration="300"/>
   <frame tileid="13" duration="300"/>
  </animation>
 </tile>
 <tile id="15">
  <animation>
   <frame tileid="15" duration="300"/>
   <frame tileid="16" duration="300"/>
  </animation>
 </tile>
 <tile id="17">
  <animation>
   <frame tileid="17" duration="300"/>
   <frame tileid="18" duration="300"/>
  </animation>
 </tile>
 <tile id="19">
  <animation>
   <frame tileid="19" duration="300"/>
   <frame tileid="20" duration="300"/>
  </animation>
 </tile>
</tileset>
