<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/blackthorn-city.tmx — do not edit.
     Holds only the 212 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="blackthorn-city-compact" tilewidth="32" tileheight="32" tilecount="212" columns="15">
 <image source="blackthorn-city.png" width="480" height="480"/>
</tileset>
