<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/cerulean-city.tmx — do not edit.
     Holds only the 256 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="cerulean-city-compact" tilewidth="32" tileheight="32" tilecount="256" columns="16">
 <image source="cerulean-city.png" width="512" height="512"/>
</tileset>
