<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/diglett-s-cave-15.tmx — do not edit.
     Holds only the 25 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="diglett-s-cave-15-compact" tilewidth="32" tileheight="32" tilecount="25" columns="5">
 <image source="diglett-s-cave-15.png" width="160" height="160"/>
</tileset>
