<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/dragon-s-den.tmx — do not edit.
     Holds only the 322 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="dragon-s-den-compact" tilewidth="32" tileheight="32" tilecount="322" columns="18">
 <image source="dragon-s-den.png" width="576" height="576"/>
</tileset>
