<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/ecruteak-city.tmx — do not edit.
     Holds only the 352 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="ecruteak-city-compact" tilewidth="32" tileheight="32" tilecount="352" columns="19">
 <image source="ecruteak-city.png" width="608" height="608"/>
</tileset>
