<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/extra.tmx — do not edit.
     Holds only the 1 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="extra-compact" tilewidth="32" tileheight="32" tilecount="1" columns="1">
 <image source="extra.png" width="32" height="32"/>
</tileset>
