<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/fuchsia-city.tmx — do not edit.
     Holds only the 342 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="fuchsia-city-compact" tilewidth="32" tileheight="32" tilecount="342" columns="19">
 <image source="fuchsia-city.png" width="608" height="576"/>
</tileset>
