<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/goldenrod-city.tmx — do not edit.
     Holds only the 480 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="goldenrod-city-compact" tilewidth="32" tileheight="32" tilecount="480" columns="22">
 <image source="goldenrod-city.png" width="704" height="704"/>
</tileset>
