<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/ice-path-b2f.tmx — do not edit.
     Holds only the 73 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="ice-path-b2f-compact" tilewidth="32" tileheight="32" tilecount="73" columns="9">
 <image source="ice-path-b2f.png" width="288" height="288"/>
</tileset>
