<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/kanto-remastered.tmx — do not edit.
     Holds only the 2 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="kanto-remastered-compact" tilewidth="32" tileheight="32" tilecount="2" columns="2">
 <image source="kanto-remastered.png" width="64" height="32"/>
</tileset>
