<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/mt-mortar.tmx — do not edit.
     Holds only the 120 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="mt-mortar-compact" tilewidth="32" tileheight="32" tilecount="120" columns="11">
 <image source="mt-mortar.png" width="352" height="352"/>
</tileset>
