<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/mt-mortar-b2f.tmx — do not edit.
     Holds only the 94 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="mt-mortar-b2f-compact" tilewidth="32" tileheight="32" tilecount="94" columns="10">
 <image source="mt-mortar-b2f.png" width="320" height="320"/>
</tileset>
