<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/mt-silver.tmx — do not edit.
     Holds only the 102 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="mt-silver-compact" tilewidth="32" tileheight="32" tilecount="102" columns="11">
 <image source="mt-silver.png" width="352" height="320"/>
</tileset>
