<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/north-rock-cave.tmx — do not edit.
     Holds only the 49 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="north-rock-cave-compact" tilewidth="32" tileheight="32" tilecount="49" columns="7">
 <image source="north-rock-cave.png" width="224" height="224"/>
</tileset>
