<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/peaceful-garden.tmx — do not edit.
     Holds only the 29 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="peaceful-garden-compact" tilewidth="32" tileheight="32" tilecount="29" columns="6">
 <image source="peaceful-garden.png" width="192" height="160"/>
</tileset>
