<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/rock-tunnel-b1f.tmx — do not edit.
     Holds only the 51 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="rock-tunnel-b1f-compact" tilewidth="32" tileheight="32" tilecount="51" columns="8">
 <image source="rock-tunnel-b1f.png" width="256" height="224"/>
</tileset>
