<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-35.tmx — do not edit.
     Holds only the 121 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-35-compact" tilewidth="32" tileheight="32" tilecount="121" columns="11">
 <image source="route-35.png" width="352" height="352"/>
</tileset>
