<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-43.tmx — do not edit.
     Holds only the 72 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-43-compact" tilewidth="32" tileheight="32" tilecount="72" columns="9">
 <image source="route-43.png" width="288" height="256"/>
</tileset>
