<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-2-70.tmx — do not edit.
     Holds only the 132 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-2-70-compact" tilewidth="32" tileheight="32" tilecount="132" columns="12">
 <image source="route-2-70.png" width="384" height="352"/>
</tileset>
