<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-29.tmx — do not edit.
     Holds only the 170 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-29-compact" tilewidth="32" tileheight="32" tilecount="170" columns="14">
 <image source="route-29.png" width="448" height="416"/>
</tileset>
