<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-26.tmx — do not edit.
     Holds only the 181 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-26-compact" tilewidth="32" tileheight="32" tilecount="181" columns="14">
 <image source="route-26.png" width="448" height="416"/>
</tileset>
