<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-41.tmx — do not edit.
     Holds only the 48 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-41-compact" tilewidth="32" tileheight="32" tilecount="48" columns="7">
 <image source="route-41.png" width="224" height="224"/>
</tileset>
