<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/route-5.tmx — do not edit.
     Holds only the 141 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="route-5-compact" tilewidth="32" tileheight="32" tilecount="141" columns="12">
 <image source="route-5.png" width="384" height="384"/>
</tileset>
