<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/saffron-city.tmx — do not edit.
     Holds only the 317 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="saffron-city-compact" tilewidth="32" tileheight="32" tilecount="317" columns="18">
 <image source="saffron-city.png" width="576" height="576"/>
</tileset>
