<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/slowpoke-well-1bf.tmx — do not edit.
     Holds only the 85 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="slowpoke-well-1bf-compact" tilewidth="32" tileheight="32" tilecount="85" columns="10">
 <image source="slowpoke-well-1bf.png" width="320" height="288"/>
</tileset>
