<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/union-cave-b2f.tmx — do not edit.
     Holds only the 62 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="union-cave-b2f-compact" tilewidth="32" tileheight="32" tilecount="62" columns="8">
 <image source="union-cave-b2f.png" width="256" height="256"/>
</tileset>
