<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/vermilion-city.tmx — do not edit.
     Holds only the 277 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="vermilion-city-compact" tilewidth="32" tileheight="32" tilecount="277" columns="17">
 <image source="vermilion-city.png" width="544" height="544"/>
</tileset>
