<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/compact-atlases.mjs from src/tiled/whirl-islands-b1f.tmx — do not edit.
     Holds only the 105 tiles that map draws, plus every frame of the
     0 animations among them, laid out so each animation is one
     unbroken row-run. Edit the originals in src/tiled/. -->
<tileset version="1.10" tiledversion="1.11.0" name="whirl-islands-b1f-compact" tilewidth="32" tileheight="32" tilecount="105" columns="11">
 <image source="whirl-islands-b1f.png" width="352" height="320"/>
</tileset>
