/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Placeholder, PlaceholderInterface } from "../Placeholder.js";

  const _abi = [
  {
    "inputs": [],
    "name": "value",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052602a5f553480156012575f5ffd5b50607980601e5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80633fa4f24514602a575b5f5ffd5b60315f5481565b60405190815260200160405180910390f3fea26469706673582212200becb5c74498e1994664c73149e594f65418628d569bc789ad49496125433a8b64736f6c634300081c0033";

  
      type PlaceholderConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: PlaceholderConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Placeholder__factory extends ContractFactory {
    
      constructor(...args: PlaceholderConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Placeholder & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Placeholder__factory {
      return super.connect(runner) as Placeholder__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): PlaceholderInterface {
      return new Interface(_abi) as PlaceholderInterface;
    }
    
    override attach(address: string | Addressable): Placeholder {
      return super.attach(address) as Placeholder;
    }
  static connect(address: string, runner?: ContractRunner | null): Placeholder {
      return new Contract(address, _abi, runner) as unknown as Placeholder;
    }
  }

  
  