// GENERATED by tools/import-maps.mjs — do not edit by hand.
import h0 from './basement.hitboxes.json'
import h1 from './battlearena.hitboxes.json'
import h2 from './beach.hitboxes.json'
import h3 from './cave.hitboxes.json'
import h4 from './cyclingroad.hitboxes.json'
import h5 from './elevator-1.hitboxes.json'
import h6 from './elevator-2.hitboxes.json'
import h7 from './exterior.hitboxes.json'
import h8 from './gamecorner.hitboxes.json'
import h9 from './hub.hitboxes.json'
import h10 from './labo.hitboxes.json'
import h11 from './library.hitboxes.json'
import h12 from './marsh.hitboxes.json'
import h13 from './photostudio.hitboxes.json'
import h14 from './river.hitboxes.json'
import h15 from './rockethq.hitboxes.json'
import h16 from './route.hitboxes.json'
import h17 from './tundra.hitboxes.json'
import h18 from './wifi.hitboxes.json'

export type Rect = { x: number; y: number; width: number; height: number }

export const MAPS: { id: string; hitboxes: Rect[] }[] = [
  { id: 'basement', hitboxes: h0 },
  { id: 'battlearena', hitboxes: h1 },
  { id: 'beach', hitboxes: h2 },
  { id: 'cave', hitboxes: h3 },
  { id: 'cyclingroad', hitboxes: h4 },
  { id: 'elevator-1', hitboxes: h5 },
  { id: 'elevator-2', hitboxes: h6 },
  { id: 'exterior', hitboxes: h7 },
  { id: 'gamecorner', hitboxes: h8 },
  { id: 'hub', hitboxes: h9 },
  { id: 'labo', hitboxes: h10 },
  { id: 'library', hitboxes: h11 },
  { id: 'marsh', hitboxes: h12 },
  { id: 'photostudio', hitboxes: h13 },
  { id: 'river', hitboxes: h14 },
  { id: 'rockethq', hitboxes: h15 },
  { id: 'route', hitboxes: h16 },
  { id: 'tundra', hitboxes: h17 },
  { id: 'wifi', hitboxes: h18 },
]
