// GENERATED by tools/import-rmxp-maps.mjs — do not edit by hand.
//
// Explicit imports, not import.meta.glob: vite.config.ts loads src/server
// in a plain Node context where import.meta.glob does not exist.
//
// Separate from ./manifest (the PSDK maps) so the two importers never
// clobber each other. To put these maps in the game, spread RMXP_MAPS
// into the MAPS list in src/modules/main/server.ts — the hitbox shape is
// identical, so the existing onBeforeUpdate hook already handles them.
import h0 from './lake-of-rage.hitboxes.json'
import h1 from './mt-mortar.hitboxes.json'
import h2 from './new-bark-town.hitboxes.json'
import h3 from './route-3.hitboxes.json'

import type { Rect } from './manifest'

export const RMXP_MAPS: { id: string; name: string; rmxpId: number; width: number; height: number; hitboxes: Rect[] }[] = [
  { id: 'lake-of-rage', name: "Lake of Rage", rmxpId: 132, width: 96, height: 70, hitboxes: h0 },
  { id: 'mt-mortar', name: "Mt. Mortar", rmxpId: 128, width: 110, height: 100, hitboxes: h1 },
  { id: 'new-bark-town', name: "New Bark Town", rmxpId: 79, width: 22, height: 48, hitboxes: h2 },
  { id: 'route-3', name: "Route 3", rmxpId: 16, width: 100, height: 84, hitboxes: h3 },
]
