// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {StockmonstersNFT} from "./StockmonstersNFT.sol";
import {StockmonstersMarket} from "./StockmonstersMarket.sol";
import {CommitVectors} from "./CommitVectors.sol";
import {Vm} from "./TestHelpers.sol";

/// JS <-> Solidity commitment cross-check.
///
/// `tools/voucher-lib.mjs` (the production signer) computes the sealed-box
/// commitment and the EIP-712 digests in viem; this contract recomputes them in
/// Solidity and then actually mints and opens with the JS-produced bytes. If
/// the two encodings ever diverge — a viem upgrade changing how `uint8[6]` is
/// padded inside `encodePacked`, a typehash edited on one side only — every
/// NFT minted in between would become PERMANENTLY UNOPENABLE. These tests are
/// the tripwire.
///
/// The vectors in CommitVectors.sol are generated by
/// `node stockmonsters-mmo/tools/gen-commit-vectors.mjs`; `--check` in CI fails
/// if the JS no longer reproduces them.
contract CommitVectorsTest {
    Vm constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    StockmonstersNFT nft;
    StockmonstersMarket market;

    /// The vectors were signed for the CREATE addresses of DEPLOYER at nonce 0
    /// and nonce 1, which is exactly what this reproduces.
    function setUp() public {
        vm.chainId(CommitVectors.CHAIN_ID);
        vm.setNonce(CommitVectors.DEPLOYER, 0);
        vm.startPrank(CommitVectors.DEPLOYER);
        nft = new StockmonstersNFT(CommitVectors.GAME_SIGNER, "ipfs://images/", "ipfs://sealed.png");
        market = new StockmonstersMarket(address(nft), CommitVectors.DEPLOYER, 250);
        vm.stopPrank();
        require(address(nft) == CommitVectors.NFT_ADDRESS, "NFT address drifted from the vectors");
        require(address(market) == CommitVectors.MARKET_ADDRESS, "market address drifted from the vectors");
    }

    /// Level 1: the pure encodings agree.
    function test_jsAndSolidityAgreeOnTheCommitment() public pure {
        for (uint256 i = 0; i < CommitVectors.COUNT; i++) {
            CommitVectors.Vector memory v = CommitVectors.vector(i);

            bytes32 solIvsHash = keccak256(abi.encodePacked(v.ivs));
            require(solIvsHash == v.ivsHash, "ivs hash: viem encodePacked(uint8[6]) != abi.encodePacked");

            bytes32 solCommit = keccak256(
                abi.encode(v.dexId, v.level, solIvsHash, v.natureId, v.shiny, v.caughtAt, v.salt)
            );
            require(solCommit == v.attrCommit, "attrCommit: JS and Solidity disagree");
        }
    }

    /// Level 2: the EIP-712 digest — typehash, field order, domain — agrees.
    function test_jsAndSolidityAgreeOnTheVoucherDigest() public view {
        bytes32 typeHash = nft.VOUCHER_TYPEHASH();
        for (uint256 i = 0; i < CommitVectors.COUNT; i++) {
            CommitVectors.Vector memory v = CommitVectors.vector(i);
            bytes32 structHash = keccak256(abi.encode(typeHash, v.player, v.attrCommit, v.uid, v.fee, v.deadline));
            bytes32 digest = keccak256(abi.encodePacked("\x19\x01", nft.DOMAIN_SEPARATOR(), structHash));
            require(digest == v.digest, "voucher digest: JS and Solidity disagree");
        }
    }

    /// Level 3: end to end. The bytes the production signer emits are accepted
    /// by the real contract, and the salt it held back really does open the box.
    function test_jsSignedVoucherMintsAndOpensOnChain() public {
        for (uint256 i = 0; i < CommitVectors.COUNT; i++) {
            CommitVectors.Vector memory v = CommitVectors.vector(i);
            vm.deal(v.player, v.fee + 1 ether);
            vm.prank(v.player);
            uint256 id = nft.mintCaught{value: v.fee}(v.attrCommit, v.uid, v.fee, v.deadline, v.signature);

            require(nft.ownerOf(id) == v.player, "minted to the voucher's player");
            require(!nft.opened(id), "arrives sealed");

            vm.prank(v.player);
            nft.open(id, v.dexId, v.level, v.ivs, v.natureId, v.shiny, v.caughtAt, v.salt);
            require(nft.opened(id), "the JS salt opens the box");

            (uint16 dexId, uint8 level,,,,,,, uint8 natureId, bool shiny, uint64 caughtAt) = nft.monsters(id);
            require(dexId == v.dexId && level == v.level, "revealed dexId/level");
            require(natureId == v.natureId && shiny == v.shiny && caughtAt == v.caughtAt, "revealed rest");
        }
    }

    /// A one-bit change to the JS-signed reveal must not open the box — proof
    /// the vectors are not passing by accident.
    function test_tamperedJsRevealIsRejected() public {
        CommitVectors.Vector memory v = CommitVectors.vector(0);
        vm.deal(v.player, v.fee + 1 ether);
        vm.prank(v.player);
        uint256 id = nft.mintCaught{value: v.fee}(v.attrCommit, v.uid, v.fee, v.deadline, v.signature);

        uint8[6] memory tampered = v.ivs;
        tampered[0] = tampered[0] == 31 ? 30 : tampered[0] + 1;
        vm.expectRevert(bytes("BAD_REVEAL"));
        vm.prank(v.player);
        nft.open(id, v.dexId, v.level, tampered, v.natureId, v.shiny, v.caughtAt, v.salt);
    }

    /// The same check for the marketplace order type.
    function test_jsAndSolidityAgreeOnTheOrderDigest() public view {
        CommitVectors.OrderVector memory ov = CommitVectors.orderVector();
        StockmonstersMarket.Order memory o = StockmonstersMarket.Order({
            seller: ov.seller,
            tokenId: ov.tokenId,
            price: ov.price,
            minProceeds: ov.minProceeds,
            deadline: ov.deadline,
            epoch: ov.epoch,
            salt: ov.salt,
            requireSealed: ov.requireSealed,
            attrCommit: ov.attrCommit,
            taker: ov.taker,
            currency: ov.currency
        });
        require(market.hashOrder(o) == ov.digest, "order digest: JS and Solidity disagree");
        require(_recover(ov.digest, ov.signature) == CommitVectors.SELLER, "order signature recovers the seller");
    }

    function _recover(bytes32 digest, bytes memory sig) private pure returns (address) {
        require(sig.length == 65, "BAD_SIG_LEN");
        bytes32 r;
        bytes32 s;
        uint8 v;
        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }
        if (v < 27) v += 27;
        return ecrecover(digest, v, r, s);
    }
}
