/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StockMonsterCollection } from './StockMonsterCollection.js';
export * as factories from './factories/index.js';
export { StockMonsterCollection__factory } from './factories/StockMonsterCollection__factory.js';