/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StockMonsterCollectionInterface extends Interface {
    getFunction(nameOrSignature: "GLOBAL_SUPPLY_CAP" | "IV_MAX" | "SHINY_ODDS_DENOMINATOR" | "approve" | "balanceOf" | "ballPrice" | "computeA" | "getApproved" | "imageBaseUri" | "isApprovedForAll" | "name" | "owner" | "ownerOf" | "registerSpecies" | "renounceOwnership" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "setImageBaseUri" | "shinyClaimed" | "species" | "supportsInterface" | "symbol" | "throwBall" | "tokenURI" | "totalMinted" | "traitsOf" | "transferFrom" | "transferOwnership" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "BrokeFree" | "OwnershipTransferred" | "SpeciesRegistered" | "StockmonsterCaught" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'GLOBAL_SUPPLY_CAP', values?: undefined): string;
encodeFunctionData(functionFragment: 'IV_MAX', values?: undefined): string;
encodeFunctionData(functionFragment: 'SHINY_ODDS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'ballPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'computeA', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'imageBaseUri', values?: undefined): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerSpecies', values: [BigNumberish[], string[], string[], BigNumberish[], BigNumberish[], BigNumberish[], BigNumberish[][]]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setImageBaseUri', values: [string]): string;
encodeFunctionData(functionFragment: 'shinyClaimed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'species', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'throwBall', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalMinted', values?: undefined): string;
encodeFunctionData(functionFragment: 'traitsOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'GLOBAL_SUPPLY_CAP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'IV_MAX', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SHINY_ODDS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ballPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'imageBaseUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerSpecies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setImageBaseUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shinyClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'species', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'throwBall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMinted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'traitsOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BrokeFreeEvent {
      export type InputTuple = [trainer: AddressLike, dexId: BigNumberish, ball: BigNumberish];
      export type OutputTuple = [trainer: string, dexId: bigint, ball: bigint];
      export interface OutputObject {trainer: string, dexId: bigint, ball: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SpeciesRegisteredEvent {
      export type InputTuple = [dexId: BigNumberish, name: string];
      export type OutputTuple = [dexId: bigint, name: string];
      export interface OutputObject {dexId: bigint, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StockmonsterCaughtEvent {
      export type InputTuple = [trainer: AddressLike, tokenId: BigNumberish, dexId: BigNumberish, shiny: boolean, level: BigNumberish];
      export type OutputTuple = [trainer: string, tokenId: bigint, dexId: bigint, shiny: boolean, level: bigint];
      export interface OutputObject {trainer: string, tokenId: bigint, dexId: bigint, shiny: boolean, level: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StockMonsterCollection extends BaseContract {
    
    connect(runner?: ContractRunner | null): StockMonsterCollection;
    waitForDeployment(): Promise<this>;

    interface: StockMonsterCollectionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    GLOBAL_SUPPLY_CAP: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    IV_MAX: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SHINY_ODDS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    ballPrice: TypedContractMethod<
      [ball: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    computeA: TypedContractMethod<
      [dexId: BigNumberish, maxHp: BigNumberish, currentHp: BigNumberish, status: BigNumberish, ball: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    imageBaseUri: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    registerSpecies: TypedContractMethod<
      [dexIds: BigNumberish[], names: string[], tickers: string[], type1s: BigNumberish[], type2s: BigNumberish[], catchRates: BigNumberish[], baseStats: BigNumberish[][], ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setImageBaseUri: TypedContractMethod<
      [newUri: string, ],
      [void],
      'nonpayable'
    >
    

    
    shinyClaimed: TypedContractMethod<
      [dexId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    species: TypedContractMethod<
      [dexId: BigNumberish, ],
      [[boolean, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {registered: boolean, name: string, ticker: string, type1: bigint, type2: bigint, catchRate: bigint, baseHp: bigint, baseAttack: bigint, baseDefense: bigint, baseSpAttack: bigint, baseSpDefense: bigint, baseSpeed: bigint }],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    throwBall: TypedContractMethod<
      [dexId: BigNumberish, level: BigNumberish, maxHp: BigNumberish, currentHp: BigNumberish, status: BigNumberish, ball: BigNumberish, ],
      [[boolean, bigint] & {caught: boolean, tokenId: bigint }],
      'payable'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalMinted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    traitsOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {dexId: bigint, level: bigint, hp: bigint, attack: bigint, defense: bigint, spAttack: bigint, spDefense: bigint, speed: bigint, shiny: boolean }],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'GLOBAL_SUPPLY_CAP'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'IV_MAX'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SHINY_ODDS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ballPrice'): TypedContractMethod<
      [ball: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'computeA'): TypedContractMethod<
      [dexId: BigNumberish, maxHp: BigNumberish, currentHp: BigNumberish, status: BigNumberish, ball: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'imageBaseUri'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerSpecies'): TypedContractMethod<
      [dexIds: BigNumberish[], names: string[], tickers: string[], type1s: BigNumberish[], type2s: BigNumberish[], catchRates: BigNumberish[], baseStats: BigNumberish[][], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setImageBaseUri'): TypedContractMethod<
      [newUri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shinyClaimed'): TypedContractMethod<
      [dexId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'species'): TypedContractMethod<
      [dexId: BigNumberish, ],
      [[boolean, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {registered: boolean, name: string, ticker: string, type1: bigint, type2: bigint, catchRate: bigint, baseHp: bigint, baseAttack: bigint, baseDefense: bigint, baseSpAttack: bigint, baseSpDefense: bigint, baseSpeed: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'throwBall'): TypedContractMethod<
      [dexId: BigNumberish, level: BigNumberish, maxHp: BigNumberish, currentHp: BigNumberish, status: BigNumberish, ball: BigNumberish, ],
      [[boolean, bigint] & {caught: boolean, tokenId: bigint }],
      'payable'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalMinted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'traitsOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {dexId: bigint, level: bigint, hp: bigint, attack: bigint, defense: bigint, spAttack: bigint, spDefense: bigint, speed: bigint, shiny: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BrokeFree'): TypedContractEvent<BrokeFreeEvent.InputTuple, BrokeFreeEvent.OutputTuple, BrokeFreeEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'SpeciesRegistered'): TypedContractEvent<SpeciesRegisteredEvent.InputTuple, SpeciesRegisteredEvent.OutputTuple, SpeciesRegisteredEvent.OutputObject>;
getEvent(key: 'StockmonsterCaught'): TypedContractEvent<StockmonsterCaughtEvent.InputTuple, StockmonsterCaughtEvent.OutputTuple, StockmonsterCaughtEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BrokeFree(address,uint16,uint8)': TypedContractEvent<BrokeFreeEvent.InputTuple, BrokeFreeEvent.OutputTuple, BrokeFreeEvent.OutputObject>;
      BrokeFree: TypedContractEvent<BrokeFreeEvent.InputTuple, BrokeFreeEvent.OutputTuple, BrokeFreeEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'SpeciesRegistered(uint16,string)': TypedContractEvent<SpeciesRegisteredEvent.InputTuple, SpeciesRegisteredEvent.OutputTuple, SpeciesRegisteredEvent.OutputObject>;
      SpeciesRegistered: TypedContractEvent<SpeciesRegisteredEvent.InputTuple, SpeciesRegisteredEvent.OutputTuple, SpeciesRegisteredEvent.OutputObject>;
    

      'StockmonsterCaught(address,uint256,uint16,bool,uint8)': TypedContractEvent<StockmonsterCaughtEvent.InputTuple, StockmonsterCaughtEvent.OutputTuple, StockmonsterCaughtEvent.OutputObject>;
      StockmonsterCaught: TypedContractEvent<StockmonsterCaughtEvent.InputTuple, StockmonsterCaughtEvent.OutputTuple, StockmonsterCaughtEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }