/**
 * One creature design brief per Robinhood Chain token.
 *
 * Each entry is the *subject* half of an image prompt: body plan, key motif,
 * palette. The generator wraps these in the shared sprite-style boilerplate and
 * the per-sprite technical spec, so keep these purely about the creature.
 *
 * Written from what each company actually does, so the roster reads as a world
 * rather than 194 logos with legs.
 */
export const DESIGNS = {
  // --- the flagship ---
  AAPL: 'a legendary cyber-lion whose mane is made of glowing blossom-petals of light, brushed-aluminium body plates, calm and regal, silver-white and soft gold',

  // --- semiconductors, fabs, optics ---
  AAOI: 'a coiled fibre-optic serpent, body of braided glass strands, pulses of laser light running head to tail, cyan and black',
  AEHR: 'a squat burn-in furnace beetle, glowing test-socket eyes, heat-shimmer carapace, ember orange',
  AEIS: 'an armoured power-cell ram, spiral horns arcing with plasma, thick industrial plating, steel blue',
  ALAB: 'a maze-shelled tortoise, interconnect traces winding across its back like a labyrinth, silver and violet',
  AMAT: 'a many-armed deposition golem, each limb a coating nozzle, wafer-disc shoulders, matte grey and gold',
  AMBA: 'a lens-eyed owl, aperture irises that dilate, feathers of thin sensor film, dusk purple',
  AMD: 'a lean four-winged raptor, red-hot core vents along its spine, forked tail like a heatsink, crimson and graphite',
  AMKR: 'a scarab with a packaged-chip shell, gold bond-wire legs, iridescent black',
  ASML: 'a monolithic standing sentinel, single slit-eye emitting extreme ultraviolet, mirror-polished obsidian body',
  AVGO: 'a broad-shouldered goliath, chest a switching matrix, cables braided into a beard, deep red and slate',
  AXTI: 'a crystalline tiger, compound-semiconductor stripes that refract light, amber and indigo',
  CBRS: 'a vast brain-coral leviathan, wafer-scale folds across its hull, quiet blue bioluminescence',
  CLS: 'a stork-legged assembly heron, precision manipulator beak, clean-room white',
  COHR: 'a prism stag, antlers splitting light into spectra, coherent white beam between the tines',
  CRDO: 'a signal-serpent with a mirrored gorget, retimer scales that repeat its own pattern, teal',
  INTC: 'an old blue basilisk, cracked fab-plate scales, dim but enormous, cobalt and rust',
  JBL: 'a workhorse pack-mule automaton, modular crates bolted to its frame, utilitarian olive',
  KLAC: 'a scanning lynx, grid-pupil eyes that sweep for defects, hairline-thin whiskers, pale gold',
  LITE: 'a lantern-jelly, transceiver bells pulsing in sequence, drifting fibre tendrils, luminous green',
  LRCX: 'a one-eyed etching cyclops, plasma-jet fist, plating scarred by its own work, dull violet',
  MPWR: 'a compact monolith badger, single-block body, dense and unsplittable, dark bronze',
  MRVL: 'a storage-drake with a spiralling data-tail, controller runes on its flanks, sea green',
  MTSI: 'a radio-wave siren, dish-shaped collar, microwave ripples where it sings, muted copper',
  MU: 'a memory-cell mammoth, hexagonal DRAM tusks, dense layered hide, industrial green',
  MXL: 'a whip-thin broadband eel, signal fins, amplifies anything it touches, electric yellow',
  NVDA: 'a colossal technological dragon that feeds on computation, GPU-fin ridges glowing under load, green fire in its throat, black and acid green',
  NVTS: 'a gallium-nitride boar, tusks arcing with fast-switching current, compact and violent, pale jade',
  ON: 'a night-black panther, power-transistor spots that flicker on and off, matte obsidian',
  ONTO: 'a metrology moth, wings patterned like inspection interferograms, iridescent silver',
  PENG: 'an armoured penguin engineer, memory-module chestplate, waddling but immovable, ice blue',
  POET: 'a photonic hummingbird, wings of etched waveguide, hovers in a halo of light, opal',
  QCOM: 'a comet-tailed lynx, modem whiskers trailing signal, streaks of blue fire',
  SIMO: 'a controller-fox, nine tails each a flash channel, quick and neat, amber',
  SKHY: 'a nine-headed memory hydra, each head a stacked HBM tower, ceramic white and blue',
  SMCI: 'a chimera of server racks, mismatched limbs from different machines, cooling fans for eyes, steel and green',
  SNDK: 'a sand-wyrm burrowing through flash storage dunes, scales of NAND wafer, desert ochre',
  TER: 'a testing colossus with probe-needle fingers, verdict lights across its chest, grey and green',
  TSEM: 'a foundry tower titan, kiln-mouth chest, specialty-process banners, brick red',
  TSM: 'the great foundry drake, forge-heart glowing through plated ribs, every scale a wafer, molten gold and slate',
  UMC: 'a legacy-node beetle, worn but reliable shell, mature and unhurried, bronze',
  VICR: 'a roaring power-brick lion, converter mane crackling, dense and loud, deep orange',
  WDC: 'a cache-hoarding dragon curled on a hoard of platters, spinning-disc wings, gunmetal',

  // --- software, cloud, security ---
  ADBE: 'a broad-winged creative moth, wing patterns shifting like layered artwork, gradient magenta and red',
  ANET: 'a switching heron, cables braided into plumage, routes anything through its beak, cobalt',
  APP: 'a grinning ad-sprite with kaleidoscope eyes, tail made of impression counters, hot pink',
  CRM: 'a sphinx wreathed in customer-record scrolls, cloud mane, asks a question before it lets you pass, sky blue',
  CRWD: 'a spectral falcon that hunts intrusions, talons of white fire, crimson and smoke',
  CRWV: 'a spider weaving racks of GPUs into a web, cooling-mist body, violet',
  CSCO: 'an ancient routing colossus, port-lined shoulders, moss growing on old infrastructure, teal and stone',
  CTSH: 'a many-handed advisory ogre, each hand holding a different process, plain grey',
  CVNA: 'a vending-machine juggernaut, cars stacked in its glass torso, tower-tall, sky blue',
  DDOG: 'a loyal telemetry hound, dashboard-glow collar, three eyes for logs, metrics and traces, purple',
  DELL: 'a modular elemental made of stacked chassis, reassembles itself mid-fight, midnight blue',
  DOCN: 'a nereid of the developer sea, droplet-shaped, small and quick, ocean blue',
  FIG: 'a many-fingered design imp, vector-node joints, redraws its own outline constantly, multicolour',
  FTNT: 'a fortress-shelled crab, firewall plating, claws that clamp shut on threats, red and steel',
  HPE: 'a winged enterprise pegasus, server-blade feathers, dependable and grey-green',
  IBM: 'an ancient blue idol-titan, mainframe monolith torso, carved punchcard runes, deep blue',
  INOD: 'a data-annotating drone-swarm that forms one bird shape, tagging everything it sees, white',
  INTU: 'a ledger-devouring toad, tongue that snatches receipts, swollen with tax season, green',
  MDB: 'a document-drake coiled around a green leaf-shaped hoard, flexible spineless body',
  MSFT: 'a four-paned colossus, window-light shining from its chest, oldest and steadiest of the tech titans, azure and grey',
  META: 'a shapeshifter with no fixed face, mirror-mask cycling through borrowed identities, infinity-loop horns, deep blue',
  NET: 'a cumulus wolf, body of edge-cloud vapour, sits between traffic and harm, orange and white',
  NOW: 'a workflow golem of interlocking ticket-plates, moves only when a process advances, green',
  ORCL: 'a cataclysm-oracle, database-tablet halo, speaks in queries, blood red and black',
  PANW: 'a firewall warden, gate-shaped shield, unblinking inspection eye, dark orange',
  PATH: 'a many-limbed automation golem, repeats one motion perfectly forever, orange',
  PLTR: 'a seeing-stone pantheon-idol, many eyes across a black monolith body, watches everything at once, obsidian and grey',
  SNOW: 'a crystalline data-wyrm, warehouse facets storing frozen light, pale blue and white',
  TEAM: 'a titan holding up a shared workspace like a sky, teammate-glyphs orbiting, deep blue',
  TTD: 'a wraith of the ad exchange, bids flickering across its shroud, appears only at auction, teal',
  WDAY: 'a daywalking timekeeper, payroll-hourglass torso, sunrise orange',
  ZM: 'a gridded phantom of floating video panes, many faces at once, sky blue',
  ZS: 'a zero-trust sceptre-serpent, checks identity at every scale, indigo',
  GOOGL: 'a vast search-golem of stacked index-stone, glowing query-eye, moss of crawled data on its shoulders, primary-colour seams',
  IREN: 'a hydro-cooled mining hydra, immersion-tank body, three cold heads, glacier blue',

  // --- consumer, media, retail ---
  AMZN: 'a gigantic jungle serpent whose body contains warehouses and endless delivery roads, conveyor scales, smile-curve jaw, deep green and orange',
  COST: 'an enormous bulk-hauling taurus, pallet-slab shoulders, membership-tag ring through its nose, red and navy',
  ELF: 'a cosmetics sprite, pigment-swirl wings, changes colour on a whim, pastel',
  KSS: 'a colossus of department-store floors, perpetual discount banners for a mane, faded gold',
  LULU: 'a lithe stretching lynx, athletic-weave fur, impossible flexibility, seafoam',
  CCL: 'a barnacled leviathan cruise-whale, deck-lights along its flank, ocean navy',
  CELH: 'a caffeinated sabre-hare, heartbeat visible through its chest, neon citrus',
  SNAP: 'a snapping ghost-jaw sprite, vanishes ten seconds after being seen, yellow',
  RDDT: 'a many-mouthed cave troll, upvote-arrow horns, gets stronger the more it is argued with, orange-red',
  RBLX: 'a blocky construct that rebuilds itself from primitive shapes, child-simple and endless, red and grey',
  TTWO: 'a two-headed beast, one head cinematic and one head chaotic, black and gold',
  NFLX: 'a long serialised ibis, feathers like episode tiles, its tail never ends, red and black',
  DJT: 'a gilded broadcast titan, tower-crown, speaks only in all-caps, gold',
  GME: 'a meme-chameleon whose power is set entirely by attention, cycles through every colour when watched, arcade-cabinet ridges',
  AMC: 'a cinema-hall eldritch thing, curtain tentacles, projector eye, popcorn-stalactite maw, deep red',
  SHOP: 'a merchant phoenix, storefront-plumage, rebuilds a shop wherever it lands, green and violet',
  SOUN: 'a howling waveform hound, ears shaped like directional mics, sound-visible breath, orange',

  // --- fintech, crypto, exchanges ---
  COIN: 'a spectral creature made of constantly shifting coins that grows stronger with speculation, no fixed body, ghostly blue and gold',
  MSTR: 'a hoarding stryx-owl perched on an enormous orange coin, leveraged wings, never sells, black and orange',
  SOFI: 'a refinancing phoenix, debt burning away into new plumage, teal and gold',
  NU: 'a violet jungle cat of the digital bank, sleek and regional, purple',
  FUTU: 'a brokerage kirin, order-book mane, moves faster than settlement, orange',
  BULL: 'a bulwark-bull, shield-shaped brow, plants itself and refuses to move, deep green',
  GLXY: 'a galaxy-serpent of crypto dust, star-field body, cosmic violet',
  CRCL: 'a perfect ring-construct, stablecoin core that never wobbles, mint green and white',
  FISV: 'a payment-rail crane, transaction-ledger wings, unglamorous and everywhere, orange',
  FICO: 'a scoring monolith-sphinx, three-digit glyph burning on its forehead, judges everyone, grey',

  // --- energy, power, nuclear ---
  BE: 'a fuel-cell kindling-beast, stacked-cell ribs glowing warm, quiet flame, ember orange',
  CEG: 'a constellation-lyon, reactor-core heart, star map across its pelt, deep blue and white',
  FLNC: 'a storage-elemental made of battery racks, absorbs and releases surges, electric teal',
  NNE: 'a small nuclear cub, containment-shell body, dangerous potential in a compact frame, yellow-green',
  OKLO: 'a fast-reactor fox, tail of spent-fuel fire, sleek and controversial, orange-black',
  SMR: 'a modular reactor turtle, small shell that hides an enormous core, slate and green',
  RUN: 'a solar stag, panel-antlers tracking the sun, warms the ground it stands on, gold',
  TE: 'a first-energy elemental, raw and unrefined, molten copper',
  VST: 'a grid-striking thunder-ox, transmission-line horns, storm grey',
  PR: 'a shale-burrowing wyrm of the Permian, rock-dust hide, crude-black sheen',
  XOM: 'an ancient furnace-idol fed on crude, refinery-flare crown, immense and unbothered, black and red',
  POWL: 'a switchgear rhino, breaker-plate hide, charges and cannot be stopped mid-arc, industrial yellow',
  PWR: 'a lineworker colossus, transmission-tower limbs, strings power across the horizon, safety orange',
  GEV: 'a vortex-winged turbine bird, three-blade wings, spins the sky, white and blue',
  GE: 'an old industrial leviathan, turbine-heart, jet-engine shoulders, weathered blue',
  MOD: 'a heat-exchange drake, radiator-fin frill, breathes cool instead of fire, copper and green',
  FIX: 'an HVAC arachnid, duct-limbs threading through buildings, galvanised silver',
  VRT: 'a cooling-tower devourer, data-centre thermal fins, drinks heat, grey and blue',

  // --- aerospace, defence, space ---
  BA: 'a vast twin-aisle wyrm, fuselage body, swept wings, weathered white and blue',
  AVAV: 'a drone-vulture, loitering wings, patient and unblinking, desert tan',
  ASTS: 'a seraph of orbital arrays, unfolding panel-wings that block out the sun, white and gold',
  AXON: 'a taser-lynx, arc between its horns, non-lethal but decisive, yellow and black',
  FLY: 'a firefly-drake, first-stage flame at its tail, small and fast off the pad, amber',
  HII: 'a shipyard-goliath, hull-plate shoulders, drags carriers behind it, sea grey',
  HWM: 'a forged-titanium giant, engineered joints, lightweight and unbreakable, bright metal',
  KTOS: 'a target-drone colossus, expendable but relentless, matte grey',
  LHX: 'a comms-raptor, encrypted-signal crest, hears everything, dark blue',
  LMT: 'a stealth-hydra, faceted radar-absorbing plates, low observable, charcoal',
  LUNR: 'a lunar monarch, regolith-dust mane, lands where nothing else can, ash grey and gold',
  PL: 'a pantheon of imaging satellites in one bird-shape, photographs the whole world daily, white',
  RCAT: 'a red drone-catamount, quadrotor whiskers, small predator of the sky, crimson',
  RDW: 'a red-wire construct, in-space assembly arms, builds itself in orbit, rust red',
  RKLB: 'a slender launch-tyr, electron-engine heart, black carbon body with a bright plume',
  SPCX: 'an exodus-titan, reusable wings that land themselves, scorched but intact, white and soot',
  VSAT: 'a satyr with a dish-shaped horn spread, beams connection to the horizon, blue and grey',
  SATS: 'an echo-satyr, orbital-slot antlers, repeats whatever it hears back at you, pale blue',
  JOBY: 'an eVTOL bird, six rotor-plumes, near-silent flight, white and blue',
  AUR: 'an autonomous-driving aurora wolf, lidar halo, drives itself, teal and violet',
  OUST: 'a lidar-owl, spinning sensor crown, sees in point clouds, deep blue',

  // --- health, bio, pharma ---
  ABCL: 'an antibody-lynx, branching Y-shaped tail-forks that lock onto targets, clinical white and cyan',
  HIMS: 'a salve-serpent, telehealth caduceus markings, discreet and direct, sage green',
  IBRX: 'an immune-system chimera, cell-cluster mane, turns the body against invaders, pale gold',
  JNJ: 'a many-armed apothecary golem, bandage wrappings, panacea vial heart, red and white',
  LLY: 'an elixir-drake, metabolic vial coiled in its chest, slims and heals, warm red',
  MRNA: 'a messenger-serpent of coiled mRNA, instruction-strand body, rewrites what it touches, red and white',
  PFE: 'a blue pill-golem, capsule-segment body, ubiquitous and unglamorous, cobalt',
  SLS: 'a small clinical-trial sprite, hope-flicker core, fragile odds, pale green',
  TEM: 'a diagnostic sphinx, patient-data constellation across its flank, predicts outcomes, deep blue',
  CLOV: 'a four-leaf clover-wyrm, insurance-luck motif, green',
  UNH: 'an enormous coverage-hydra, one head for every plan, cut one and it bills you twice, blue and white',

  // --- quantum ---
  IONQ: 'a trapped-ion quark-moth, particles suspended in its wing-lattice, laser-cooled, violet and white',
  QBTS: 'an annealing wyrm, superconducting coil body, settles into the lowest-energy shape, chrome and blue',
  QUBT: 'a photonic qubit sprite, exists in two poses at once, shimmering teal',
  RGTI: 'a superconducting typhon, chandelier-cryostat body hanging in cold, gold and frost',
  XNDU: 'a photonic dreamer, squeezed-light plumage, half-real, opal and violet',
  INFQ: 'a neutral-atom equine, lattice-trap mane, cold and precise, pale blue',

  // --- ETFs and baskets ---
  BND: 'a bond-warden tortoise, laddered-maturity shell, slow, dull and unkillable, muted brown',
  EWT: 'a formosa-saur, island-shaped shell, fabs terraced down its back, jade green',
  EWY: 'a han-dragon of heavy industry, shipyard and memory-fab scales, deep red and steel',
  GLD: 'a gilded drake sleeping on a vault floor, solid gold scales, moves only in crises',
  INDA: 'an avatar-elephant of the subcontinent, many-armed, saffron and green',
  QQQ: 'a nasdaq-drake with a hundred wings, each wing a different tech company, iridescent',
  SCHD: 'a dividend-drake that sheds a golden scale every quarter, patient and unflashy, bronze',
  SGOV: 'a vault-golem holding short-dated paper, absolutely inert, concrete grey',
  SHY: 'a shy treasury-siren, hides at the shallow end of the curve, pale blue',
  SLV: 'a silver wyrm, mirror-bright scales, industrial and monetary at once',
  SMH: 'a helix-serpent of the whole semiconductor cycle, boom and bust coiled together, chrome',
  SOXX: 'a monolith of stacked silicon slabs, the sector rendered as one standing stone, grey and green',
  SPMO: 'a momentum-tyr, always accelerating, trails motion-blur afterimages, electric yellow',
  SPY: 'a colossal market-tyrant, five hundred eyes across its body, when it moves everything moves, deep red and white',
  VTI: 'a total-market titan, every sector fused into one enormous calm body, granite and green',
  XLK: 'a tech-sector kraken, one tentacle per megacap, ink of pure data, deep blue',
  USO: 'a leviathan of crude, oil-slick hide, rises and collapses on rumour, black rainbow sheen',

  // --- crypto mining and AI infrastructure ---
  CLSK: 'a spark-kraken, immersion-cooled tentacles, hash-rate lightning between its arms, teal and black',
  WULF: 'a nuclear-powered dire wolf, cooling-vapour breath, terawatt-blue eyes',
  APLD: 'a data-centre hydra rising out of prairie ground, transformer-heads, dust and steel',
  WYFI: 'a white-fibre serpent, glowing filament body, threads between buildings, pearl',
  NBIS: 'a nebula-basilisk, GPU-cluster coils, born from an older empire, deep violet',

  // --- autos, industrials, materials, misc ---
  TSLA: 'an electric kaiju that generates lightning when enraged, battery-cell spine, storm building around it, chrome red and white',
  F: 'an old blue work-drake, pickup-bed shoulders, dented and still running, oval blue',
  RIVN: 'a leviathan of the wilderness, adventure-rack ridges, quad-motor limbs, forest green and yellow',
  CIEN: 'a deep-sea cable serpent, transoceanic body, glowing at every repeater, abyss blue',
  GLW: 'a glass-wyrm, gorilla-tough transparent scales, refracts every attack, clear and green',
  BABA: 'a vast merchant roc, cargo-laden wings, carries an entire market on its back, orange',
  BB: 'a black-thorn briar beast, keyboard-scale hide, security thorns, dark grey',
  UPS: 'a surge-beetle of logistics, parcel-shell, brown and gold, never late',
  USAR: 'a rare-earth onyx golem, magnet-veins glowing through stone, strategic and scarce, dark violet',
  NAVN: 'a nomadic travel-sprite, itinerary wings, always in transit, sky blue',
  P: 'a purified water-spirit, absolutely clear body, filters whatever passes through, pale cyan',
};
